# Generated by Django 5.2.4 on 2026-02-14 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectvarity',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
